demos/lecture12/flask_app/models.py
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from . import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.objects(username=user_id).first()


class User(db.Document, UserMixin):
    username = db.StringField(required=True, unique=True)
    email = db.EmailField(required=True, unique=True)
    password = db.StringField(required=True)

    def get_id(self):
        return self.username


class Post(db.Document):
    title = db.StringField(required=True)
    date = db.StringField(required=True)
    content = db.StringField(required=True)
    author = db.ReferenceField(User, required=True)

    def get_title(self):
        return self.title

demos/lecture12/flask_app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import InputRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user

from ..models import User


class RegistrationForm(FlaskForm):
    username = StringField(
        "Username", validators=[InputRequired(), Length(min=2, max=30)]
    )
    email = StringField("Email", validators=[InputRequired(), Email()])
    password = PasswordField("Password", validators=[InputRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[InputRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = User.objects(username=username.data).first()
        if user is not None:
            raise ValidationError("Username is taken")

    def validate_email(self, email):
        user = User.objects(email=email.data).first()
        # user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError("Email is taken")


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[InputRequired()])
    password = PasswordField("Password", validators=[InputRequired()])
    submit = SubmitField("Login")


class UpdateForm(FlaskForm):
    username = StringField(
        "Username", validators=[InputRequired(), Length(min=2, max=30)]
    )
    submit = SubmitField("Update")

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user is not None:
                raise ValidationError("That username is already taken")

demos/lecture12/flask_app/__init__.py
from flask import Flask
from flask_talisman import Talisman
from flask_mongoengine import MongoEngine
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

app = Flask(__name__)
app.config["SECRET_KEY"] = b"\xe6\x86\xbc\x0b\x9a4\xeb\xe4\xd2\x9d\x1b\xfaF\x11\x95q"

app.config["MONGODB_HOST"] = "mongodb://localhost:27017/wk12"

talisman = Talisman(app)
db = MongoEngine(app)
login_manager = LoginManager(app)
login_manager.login_view = "users.login"
bcrypt = Bcrypt(app)

from flask_app.main.routes import main  # Blueprint class
from flask_app.users.routes import users

app.register_blueprint(main)
app.register_blueprint(users)

demos/lecture12/flask_app/main/routes.py
from flask import render_template, request, Blueprint
from flask_app.models import Post

main = Blueprint("main", __name__)


@main.route("/")
def index():
    # posts = Post.query.all()
    posts = Post.objects()
    return render_template("index.html", title="Home", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title="About")

demos/lecture12/flask_app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_mongoengine import MongoEngine
from flask_login import login_user, current_user, logout_user, login_required

from .. import bcrypt
from ..models import User, Post
from .forms import RegistrationForm, LoginForm, UpdateForm

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    return "Register"


@users.route("/login", methods=["GET", "POST"])
def login():
    return "Login"


@users.route("/logout")
def logout():
    return "Logout"


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    return "Account"


@users.route("/user/<username>")
def user_detail(username):
    return "User detail"

demos/lecture12/flask_app/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h2>About</h2>
    <p>This is a sample Flask app that manages users and keeps track of posts. It does not allow creating new posts, however.</p>
{% endblock %}

demos/lecture12/flask_app/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div>
        <a href={{ url_for('users.logout' )}}>Log Out</a>
    </div>
    <div>
        <h2>{{ current_user.username }}</h2>
        <p>{{ current_user.email }}</p>
    </div>
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label }}
                {{ form.username }}

                {% if form.username.errors %}
                    <div>
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit }}
            </div>
        </form>
    </div>
    <div>
        <h3>Your posts:</h3>
    </div>
    {% for post in current_user.posts %}
    <article>
        <div>
            <div>
                {{ post.author.username }}
                <small>{{ post.date.strftime('%B %d, %Y') }}</small>
            </div>
            <h2>{{ post.title }}</h2>
            <p>{{ post.content }}</p>
        </div>
    </article>
{% endfor %}
{% endblock %}

demos/lecture12/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask App</title>
    {% endif %}
</head>
<body>
    {% if current_user.is_authenticated %}
    <div>
        <h3>{{ current_user.username }}'s session</h3>
    </div>
    {% endif %}
    <div>
        <a href={{ url_for('main.index') }}>Home</a> <a href={{ url_for('main.about') }}>About</a> <a href={{ url_for('users.account') }}>My Account</a>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

demos/lecture12/flask_app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h2>Posts</h2>
    </div>
    {% for post in posts %}
        <article>
            <div>
                <div>
                    <a href={{ url_for('users.user_detail', username=post.author.username) }}>{{ post.author.username }}</a>
                    <small>{{ post.date.strftime('%B %d, %Y') }}</small>
                </div>
                <h2>{{ post.title }}</h2>
                <p>{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock %}

demos/lecture12/flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h2>Log In</h2>
    </div>
    <div>
        If you <b>don't</b> have an account, then <a href={{ url_for('users.register') }}>Register!</a>
    </div>
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label}}
                {{ form.username }}
                {% if form.username.errors %}
                <div>
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
            </div>
            <div>
                {{ form.password.label }}
                {{ form.password }}
            </div>
            <div>
                {{ form.submit }}
            </div>
        </form>
    </div>
{% endblock %}

demos/lecture12/flask_app/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h2>Registration</h2>
    </div>
    <div>
        If you already have an account, then just <a href={{ url_for('users.login') }}>Log In!</a>
    </div>
    <!-- Registration Form: -->
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label }}
                {{ form.username }}
                {% if form.username.errors %}
                    <div>
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.email.label }}
                {{ form.email }}
                {% if form.email.errors %}
                    <div>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.password.label }}
                {{ form.password }}
                {% if form.password.errors %}
                    <div>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.confirm_password.label }}
                {{ form.confirm_password }}
                {% if form.confirm_password.errors %}
                    <div>
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit }}
            </div>
        </form>
    </div>

{% endblock %}

demos/lecture12/flask_app/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
    <div>
        {{ user.username }}'s Posts
    </div>
    {% for post in user.posts %}
    <article>
        <div>
            <div>
                <a href={{ url_for('users.user_detail', username=post.author.username) }}>{{ post.author.username }}</a>
                <small>{{ post.date.strftime('%B %d, %Y') }}</small>
            </div>
            <h2>{{ post.title }}</h2>
            <p>{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
{% endblock %}