demos/lecture12_updated/flask_app/models.py
from datetime import datetime
from flask import current_app
from . import db


class User(db.Document):
    username = db.StringField(required=True, unique=True)

demos/lecture12_updated/flask_app/main/forms.py
from tokenize import String
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import Length, InputRequired


class PopulateForm(FlaskForm):
    submit = SubmitField("Click here to populate the web app with data!")


class DerivativeForm(FlaskForm):
    equation = StringField(
        "Equation/Expression",
        validators=[
            InputRequired(),
            Length(min=1, message="Equation/Expression is empty!"),
        ],
    )
    variable = StringField(
        "Variable differentiating with respect to",
        validators=[
            InputRequired(),
            Length(
                min=1,
                max=1,
                message="Must be a single variable expression, i.e. 'x', 'y', etc.",
            ),
        ],
    )
    submit = SubmitField("Calculate the derivative!")

demos/lecture12_updated/flask_app/__init__.py
from flask import Flask
from flask_mongoengine import MongoEngine
from flask_bcrypt import Bcrypt
from flask_login import LoginManager


# Create extension objects
db = MongoEngine()

# import blueprints
from .main.routes import main_bp

def create_app():
    app = Flask(__name__)

    app.config.from_pyfile("config.py", silent=False)

    # initialize extensions
    db.init_app(app)

    app.register_blueprint(main_bp)

    return app

demos/lecture12_updated/flask_app/main/routes.py
from bs4 import BeautifulSoup
from flask import render_template, request, Blueprint, redirect, url_for, flash
import plotly.graph_objects as go
import requests
from sympy.parsing.sympy_parser import parse_expr
from sympy import symbols, diff, latex

from collections import Counter
import io
import random
import string

from .forms import DerivativeForm, PopulateForm
from ..models import User


main_bp = Blueprint("main_bp", __name__)


def populate_sample_data():
    usernames = [
        "USERNAME",
        "PASSWORD",
        "EMAIL",
        "CAPTCHA",
        "REQUESTS",
        "SECLISTS",
        "PYTHON",
        "FLASK",
        "JAVASCRIPT",
        "HTML",
        "CSS",
    ]

    pop = string.ascii_letters

    for _ in range(50):
        rand_user = "".join(random.choices(pop, k=random.randint(8, 25)))
        usernames.append(rand_user)

    for name in usernames:
        user = User(username=name)
        user.save()


@main_bp.route("/", methods=["GET", "POST"])
def index():
    form = PopulateForm()
    if form.validate_on_submit():
        num_users = User.objects().count()

        if num_users == 0:
            populate_sample_data()

            flash("Populated the database with sample data!")
        else:
            flash("Database is already filled with sample data!")

    return render_template("index.html", title="Home", form=form)


# Note: should use the DELETE http method normally
@main_bp.route("/clear_db", methods=["GET"])
def clear_db():
    User.drop_collection()

    flash("Cleared the database!")

    return redirect(url_for("main_bp.index"))


@main_bp.route("/plotly")
def plotly():
    users = User.objects()

    names_string = "".join(user.username for user in users)
    frequencies = list(names_string)

    fig = go.Figure(data=[go.Histogram(x=frequencies)])
    f = io.StringIO()
    fig.write_html(f)

    return render_template("plot.html", plot=f.getvalue())


@main_bp.route("/dummy_request")
def dummy_request():
    r = requests.post("https://httpbin.org/post", data={"key": "value"})

    return render_template("dummy_request.html", title="Dummy Request", response=r)


# Note: not necessarily an equation; the string might just be an expression.
@main_bp.route("/derivative", methods=["GET", "POST"])
def derivative():
    form = DerivativeForm()
    if form.validate_on_submit():
        eq_str = form.equation.data
        try:
            equation = parse_expr(eq_str)
            var = symbols(form.variable.data)
        except Exception as e:
            flash(f"Received error when processing your input: {str(e)}")
            return render_template("sympy.html", form=form)

        result = latex(diff(equation, var))
        return render_template("sympy.html", form=form, derivative=result)

    return render_template("sympy.html", form=form)


# Note: requires a lot more processing to be nice to see/use for a real website
@main_bp.route("/table-parser")
def table_parser():
    url = "https://en.wikipedia.org/wiki/List_of_most-streamed_artists_on_Spotify"
    resp = requests.get(url)
    content = resp.content

    root = BeautifulSoup(content, "html.parser")
    tables = root.find_all("table")

    return render_template("table_parser.html", tables=tables)


@main_bp.route("/about")
def about():
    return render_template("about.html", title="About")

demos/lecture12_updated/flask_app/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h2>About</h2>
    <p>This is a sample Flask app that manages users and keeps track of posts. It does not allow creating new posts, however.</p>
{% endblock %}

demos/lecture12_updated/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask App</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

demos/lecture12_updated/flask_app/templates/dummy_request.html
{% extends "header.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            Trying out <code>requests.post('https://httpbin.org/post', data = {'key':'value'})</code>
        </div>
    </div>
    <div class="row">
        <div class="col">
            Response:
            <div>
                <code>
                    {{ response.text }}
                </code>
            </div>
        </div>
    </div>
</div>
{% endblock %}

demos/lecture12_updated/flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main_bp.index') }}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main_bp.plotly') }}">
                    Plotly
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main_bp.clear_db') }}">
                    Clear the Database
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main_bp.dummy_request') }}">
                    Dummy Request
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main_bp.derivative') }}">
                    Derivative
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main_bp.table_parser') }}">
                    Table Parser
                </a>
            </li>
        </ul>
    </div>
</nav>

<!-- Main content, override in child templates -->
{% block content %}{% endblock %}

{% endblock %}

demos/lecture12_updated/flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form action="" class="form-inline my-2 my-lg-0" method="POST">
                {{ form.csrf_token }}
                {{ form.submit(class="btn btn-outline-success") }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

demos/lecture12_updated/flask_app/templates/plot.html
{% extends "header.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <iframe style="width: inherit; height: 1000;" srcdoc="{{ plot }}" frameborder="0"></iframe>
        </div>
    </div>
</div>
{% endblock %}

demos/lecture12_updated/flask_app/templates/sympy.html
{% extends "header.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div>
                Please enter an expression or equation in SymPy (Python) notation to calculate the derivative.
                For example, you could enter 
                <code>x ** 2 + 2 * x + 1</code> in the first box and 
                <code>x</code> into the second box, and you should get 
                \(2x + 2\)
            </div>
            <form action="" class="my-2 my-lg-0" method="post">
                <div class="form-group">
                    {{ form.csrf_token }}

                    {{ form.equation.label }}
                    {{ form.equation(class="form-control") }}
    
                    {% if form.equation.errors %}
                    <div class="alert alert-warning" role="alert">
                      {% for error in form.equation.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.variable.label }}
                    {{ form.variable(class="form-control") }}
    
                    {% if form.variable.errors %}
                    <div class="alert alert-warning" role="alert">
                      {% for error in form.variable.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                    {% endif %}
    
                    {{ form.submit(class="btn btn-outline-success") }}
                </div>
            </form>
        </div>
    </div>

    {% if derivative %}
    <div class="row">
        <div class="col">
            The result is: $${{ derivative }}$$
        </div>
    </div>
    {% endif %}

{# Scripts for MathJax for visualizing Math #}
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

</div>
{% endblock %}

demos/lecture12_updated/flask_app/templates/table_parser.html
{% extends "header.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            List of most streamed artists on Spotify:

            {% for table in tables %}
            <div>
                <iframe style="width: 70vw; height: 300;" srcdoc="{{ table }}" frameborder="0"></iframe>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

demos/lecture12_updated/flask_app/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
    <div>
        {{ user.username }}'s Posts
    </div>
    {% for post in user.posts %}
    <article>
        <div>
            <div>
                <a href={{ url_for('users.user_detail', username=post.author.username) }}>{{ post.author.username }}</a>
                <small>{{ post.date.strftime('%B %d, %Y') }}</small>
            </div>
            <h2>{{ post.title }}</h2>
            <p>{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
{% endblock %}